### ISSUE TITLE
Highlight the current tree

### ISSUE THREAD

**Issue by bjarnef** [dellykaos/uContactor#1]
I think it would be great to highlight the current tree node :)

https://our.umbraco.org/forum/developers/extending-umbraco/63267-Custom-section-mark-currentNode-blue?p=0#comment213103

```
navigationService.syncTree({ tree: 'analyticsTree', path: ["-1", $routeParams.id], forceReload: false });
```

You can see how it is done here: https://github.com/warrenbuckley/Analytics/pull/36/files

Notice if you had (or maybe later) more levels in the trees you have to specify the comma separated path with keys like this:

```
navigationService.syncTree({ tree: 'analyticsTree', path: ["-1", "ecommerce", $routeParams.id], forceReload: false });
```

**Comment by dellykaos** [comment]
Thank you for your feedback bjarne, it's already fixed here https://github.com/dellykaos/uContactor/commit/c61827663798f7b602d1ad7f0f37615a2a10648b
