### ISSUE TITLE
localize validations error message 

### ISSUE THREAD

**Issue by makhalaf** [dellykaos/uContactor#4]
localize validations error message

**Comment by dellykaos** [comment]
can you elaborate more?

**Comment by makhalaf** [comment]
Localize data annotations attributes in ContactFormModel by making it read from predefined dictionary items

**Comment by dellykaos** [comment]
Fixed in here https://github.com/dellykaos/uContactor/commit/b08b30f73e0dedd2c07b79b00ada92930560744a
