### ISSUE TITLE
Sending message causing crash of site

### ISSUE THREAD

**Issue by ivankrzak** [dellykaos/uContactor#6]
Hi, 
Love simplicity of your plugin , Im just getting erro when someone is sending message from the site, message will arrive just user will not be redirected to home page . It causes users to try send message one more time and later write directly from mail.
Attaching image of error I am getting.
Using Merchello shoping system. 
![error](https://user-images.githubusercontent.com/29810931/27759953-658add04-5e3c-11e7-9407-1408b2da4b40.jpg)
Thank for help :)

**Comment by dellykaos** [comment]
Hi Ivan,

I think it's because your smtp setting is not correctly configured, because the error says that your server could not established connection to smtp server

**Comment by ivankrzak** [comment]
Have you some clues ? What exacly could be wrong  ?

**Comment by dellykaos** [comment]
I think your server can't connect to smtp server. Have you tried this package locally?
